### ISSUE TITLE
Code 1010 on OSX with gpg2 installed via brew.

### ISSUE THREAD

**Issue by ghost** [placetopay/php-gnupg#2]
Only checks /usr/local/bin/gpg2; brew installed path is /usr/local/MacGPG2/gpg2
Tried working around with a symbolic link, but is_executable doesn't work with links.

**Comment by placetopay** [comment]
You must pass the gpg path in the constructor.

$gpg = new \PlacetoPay\GnuPG\GnuPG([
    'gpgExecutable' => 'your gpg path',
    'ringPath' => 'your home directory ring path'
]);
